# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ab93bd93ea5dcc817b2475a1158f7703d43a24eb3805155b0cd922b93ddcfad713fecfc77309dfc67f5cd80b50824d1a521df9b22c708814b9adfb04587c456

test:
  secret_key_base: 51f828ab0deceac72c3ac9809265442a36f77319f23ba433dba5361ecab5e4feb1e23071f0605fda6747e7a9c5fd1b4c66bcdd61070a1848f3cdb66952f8a14b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
